### PR TITLE
Add windows support

### PR DESCRIPTION
**Pull request by cmosguy**
Hey @fideloper 

The Windows support is here!  Everything works beautifully, so please let me know if you have any comments or suggestions.  I have updated the readme docs as well.

Cheers!

### CODE REVIEW

**Comment by fideloper** [comment]
Nice!!! Lots simpler than I imagined.

I’ll get this pulled in for a 1.2 (well, prob 2.0) release which has a
breaking change.

Really appreciate your help!

**Comment by fideloper** [comment]
The conflicts here are super minimal, but the only important part that might be a miss was that `SEDCMD` isn't set on Windows machines. 

Do Windows machines not need the `init` command to make the vessel command executable? (I gotta test it out!)

**Comment by cmosguy** [comment]
@fideloper to answer your question, when we install Git for windows, it installs bash which is part of the `mingw64` system that allows you to run a bash shell in windows.  Included in this, is the `sed` command, so any commands you use will work.  I placed a note about this in the readme.

I am trying to understand what to do about the conflicts.  The resolve conflicts here on github is not enabled for me as I do not have write access.

**Comment by cringer** [comment]
I haven't dug into the inner workings of this package yet but I can tell you labeling everything in the README "Git Bash for Windows" is going to cause confusion.  I realize that you are referring to the  "Git Bash" that comes with "Git for Windows" but with WSL (Windows Subsystem for Linux) becoming more widely used we should probably use the proper names as WSL is called "Bash Ubuntu on Windows" and is likely going to be confused.

With that being said we should also test this within WSL.  I can tell you that a `$(which uname)` will return "Linux" in WSL.  It might work natively in that environment but I haven't tested it yet.  I plan on testing this in my environment tonight.

Just wanted to bring these things to your attention.
Also @fideloper we can't see the merge conflicts on the PR.

**Comment by fideloper** [comment]
Thanks @cringer !

**Comment by cringer** [comment]
I applied the Fall Creators Update on my system yesterday and verified my dev environment.  It looks like what used to be called "Bash Ubuntu on Windows" is now simply called "Ubuntu".

I ran through the installation steps based on the Vessel doc and I got an error running the init script.

vessel_init

Docker is installed and working correctly.
vesse-docker-compose

Based on the script it looks like its the following block it's executing
```
# Is the environment running
PSRESULT="$(docker-compose ps -q)"
if [ ! -z "$PSRESULT" ]; then
    EXEC="yes"
else
    EXEC="no"
fi
```

If I run the command outside of the bash script I do get output, though I don't know if their are supposed to be values here.

vessel-docker-ps

**Comment by fideloper** [comment]
It looks to me like you didn’t try out this branch that made changes for
windows support right? The two errors are the ones looking for the network
interface docker0 (that’s not a thing on windows), and that docker-compose
is not installed (I’m not sure if Docker in windows provides that but I
imagine it does).

I think this PR takes care of the network issue but I’m not sure about
Docker-compose. I have Bootcamp setup on my iMac with latest windows 10
update - however I’m not sure when I’ll have time to test with a 1-mo year
old taking a lot of our time in the near term :D

**Comment by cringer** [comment]
@fideloper Ah, crap your right.  I just pulled down the master.  Checking again.  🤦

**Comment by cringer** [comment]
I was hoping that WSL would work natively with the package but that's not the case.
I tried cmosguy:add-windows-support but it has the same issues as logged above.

When using "Git Bash" the install seems to go through.
vessel-mingw

But the start command bombs.
vessel

**Comment by cringer** [comment]
I have a second development machine I can check when I get home tonight.  Maybe something with my environment if @cmosguy has it working when he tested.

**Comment by cringer** [comment]
Home development machine is a brand new Windows 10 Version 1709 OS Build 16299.19

Tested the installation with the windows fork using Git Bash and it bombed out exactly the same way as in my animated .gif above.

```
85b1f47fba49: Pulling fs layer
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 68, in main
  File "compose\cli\main.py", line 121, in perform_command
  File "compose\cli\main.py", line 938, in up
  File "compose\project.py", line 430, in up
  File "compose\service.py", line 317, in ensure_image_exists
  File "compose\service.py", line 922, in build
  File "compose\progress_stream.py", line 44, in stream_output
  File "compose\progress_stream.py", line 63, in print_output_event
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Failed to execute script docker-compose
```

**Comment by cmosguy** [comment]
@cringer I've seen this issue before when @fideloper came out with the php app series and I stumbled on something almost similar but not quite:

https://github.com/shipping-docker/php-app/issues/19#issuecomment-267778718


Are you using the native docker built into windows:
image


If not, you mentioned `docker-machine` can you try to make sure you've run this command:

```bash
eval $("C:\Program Files\Docker Toolbox\docker-machine.exe" env)
```

Then execute the:
```bash
./vessel start
```

**Comment by cringer** [comment]
I am running the native docker for windows which uses Hyper-V.

docker

The referenced comment is interesting as it has the same error output but references Docker Toolbox which is a Legacy install.  My system(s) are current so they use Docker for Windows.

Just out of curiosity what is your dev environment that you are working on?  I notice your Docker CE is older then my version.

**Comment by cmosguy** [comment]
@cringer yeah, my company won't update the windows version, and for some reason docker for window will not update to the 17.09.0 version because the windows is not updated.

Anyways, what environment variables do you need specifically?

**Comment by cringer** [comment]
So there appears to be an issue with ./vessel init and ./vessel start

For init, the substitutions were not working.
```
VESSEL: Setting .env Variables
./vessel: line 90: s/DB_HOST=.*/DB_HOST=mysql/: No such file or directory
./vessel: line 91: s/CACHE_DRIVER=.*/CACHE_DRIVER=redis/: No such file or directory
./vessel: line 92: s/SESSION_DRIVER=.*/SESSION_DRIVER=redis/: No such file or directory
./vessel: line 93: s/REDIS_HOST=.*/REDIS_HOST=redis/: No such file or directory
```

I tracked this down in the initial script:
```
echo "VESSEL: Setting .env Variables"
cp .env .env.vessel
$SEDCMD "s/DB_HOST=.*/DB_HOST=mysql/" .env
$SEDCMD "s/CACHE_DRIVER=.*/CACHE_DRIVER=redis/" .env
$SEDCMD "s/SESSION_DRIVER=.*/SESSION_DRIVER=redis/" .env
$SEDCMD "s/REDIS_HOST=.*/REDIS_HOST=redis/" .env
```

The problem is the $SEDCMD variable is not defined on Windows10.  The detection piece at the top of the script only sets XDEBUG_HOST but does not set SEDCMD.  I set this in the detection block and now the substitutions are working correctly.

```
elif [ "$MACHINE" == "Windows10" ]; then
    export XDEBUG_HOST=10.0.75.1
    SEDCMD="sed -i"
fi
```

For ./vessel start I'm still looking at it.  If I try to run the actual command that should be sent from vessel in the terminal `winpty docker-compose -f docker-compose.yml up -d` I get 
```
WARNING: The WWWUSER variable is not set. Defaulting to a blank string.
WARNING: The XDEBUG_HOST variable is not set. Defaulting to a blank string.
WARNING: The APP_PORT variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
services.mysql.ports is invalid: Port ranges don't match in length
services.app.ports is invalid: Port ranges don't match in length
```

This is likely by design though as the docker-compose.yml has a lot of ${ } values which are only defined in the script.  I tried manually setting these in the terminal but docker-compose.yml doesn't pick them up.

**Comment by cringer** [comment]
One thing to also note is that `winpty` is only needed if running Mintty in as the console for Git Bash.  If during the install of Git Bash the user chose 'Use Windows' default console window' then `winpty` is not needed.

From my experience more often then not people do use Mintty.  However, with the changes to the Command Prompt since Windows 7 it's becoming more mainstream.

**Comment by cringer** [comment]
Well the good news is I got it working using "Git Bash" on my dev environment at home.

I ended up pulling down the master instead of @cmosguy PR  and then modifying the `vessel` file directly.  I made changes that mostly mimic #20 but I had to change a few things. 

I'm testing on my dev laptop today so if that checks out I'll check using WSL as well.

**Comment by cringer** [comment]
On my laptop I get an error creating the app server

```
reating vessel_node_1 ...
Creating vessel_redis_1 ...
Creating vessel_app_1 ...
Creating vessel_mysql_1 ...
Creating vessel_redis_1
Creating vessel_app_1
Creating vessel_node_1
Creating vessel_app_1 ... error

ERROR: for vessel_app_1  Cannot start service app: driver failed programming external connectivity on endpoint vessel_app_1 (4653fb9ec8c0c                              c7ddc259fc6f58c2353a00cdef41c27cc67ae38a8261bebab32): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error Permission deni                              Creating vessel_mysql_1 ... done

ERROR: for app  Cannot start service app: driver failed programming external connectivity on endpoint vessel_app_1 (4653fb9ec8c0cc7ddc259f                              c6f58c2353a00cdef41c27cc67ae38a8261bebab32): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error Permission denied
Encountered errors while bringing up the project.
```

I verified that the shares are enabled and have the correct password.  The only difference between this machine and my home one is the laptop is joined to a work domain.

Any ideas on this one?

**Comment by fideloper** [comment]
Is that windows? You’ll need permissions to bind to port 80, which may mean
running as administrator?

**Comment by cringer** [comment]
Yep on my Windows10 laptop same build as listed above.

I checked to make sure port 80 wasn't in use.  But it's definitely happening when trying to bind to port 80.  I tried creating a stand-alone nginx container binding to port 80 and got the same issue.

I even opened "Git Bash" as administrator which gave the same error.  I'll do some research on this but this is pretty odd when the only disconnect between my two machines is that this one is domain joined.  I do have local administrator rights on both machines so you'd think it would work.  🤷‍♂️

**Comment by cringer** [comment]
Ok, so I tested port 80 wasn't in use by browsing to localhost.  However, that wasn't a very good test.  Determined that the World Wide Web publishing service was started taking over port 80.  I stopped that and now the builds work correctly.  Not sure why this service is on this machine.

Testing in WSL now.

**Comment by cringer** [comment]
I was able to get working in WSL as well.  Working across the board for me now!

You guys have a suggestion for the best way for me to give you my changes?  I can list them all here for @cmosguy to update and test in #20, I can submit a new PR or I can create a PR to @cmosguy repo.

**Comment by cringer** [comment]
I ended up just creating PR #26 
All the notes are in that PR.

**Comment by fideloper** [comment]
We’ll check it out, thanks! Appreciate your work on this!

**Pull request closed without merging**
