### PR TITLE
Update to PHP7.4

### PR DESCRIPTION
**Pull request by fideloper**
Looks like xDebug is ready for release already too!

### CODE REVIEW

**Comment by fideloper** [comment]
Anyone here who approved this PR tested it out yet? I’ve only lightly tested it but I have a fresh kid at home and less time for the next month or so :D

**Comment by Jamesking56** [comment]
Docker is just rebuilding, will comment the result shortly

**Comment by fideloper** [comment]
thanks!

**Comment by vinayakkulkarni** [comment]
Tested it from my side too!

**Comment by vinayakkulkarni** [comment]
@fideloper: mate, this PR will ensure all dependencies are upto date: https://github.com/shipping-docker/vessel/pull/131

**Comment by vinayakkulkarni** [comment]
@fideloper Can you do a new release so I can pull the latest code with php7.4?

**Comment by fideloper** [comment]
Yep, tagged `5.0.0`!

**Pull request merged**
