### PR TITLE
feat: add support for semantic-pull-requests

### PR DESCRIPTION
**Pull request by vinayakkulkarni**
- [x] Adds support for [semantic-pull-requests](https://github.com/apps/semantic-pull-requests)

### CODE REVIEW

**Comment by vinayakkulkarni** [comment]
@fideloper thoughts on this?

**Comment by vinayakkulkarni** [comment]
bump 🛎

**Comment by vinayakkulkarni** [comment]
Bump 🛎

**Comment by fideloper** [comment]
I’ll get to this when I get to this dude, my life is busy.

**Comment by fideloper** [comment]
Hi again! This comment came on the heals of my 2 year old having a meltdown for 45 minutes during an important phone call I had, sorry for my tone.

That being said, the point still stands - my life is current very busy! I'll get to this...eventually.
Thanks!

**Comment by mikeerickson** [comment]
You don’t need to apologize or justify yourself. Simply not necessary.  You have done a lot for this community. You are a dad and husband FIRST and keep your eyes on that alone.

**Comment by vinayakkulkarni** [comment]
> Hi again! This comment came on the heals of my 2 year old having a meltdown for 45 minutes during an important phone call I had, sorry for my tone.

Family always comes first man! Thanks a ton for your contributions to the OSS community!

**Pull request closed without merging**
